### PR TITLE
Upgrade ktlint -> 0.42.0

### PR DESCRIPTION
**Pull request by Mahoney**
Fixes a nasty performance bug: https://github.com/pinterest/ktlint/issues/1135

### CODE REVIEW

**Comment by Mahoney** [comment]
Wow. Didn't expect that to break the world!

**Comment by Mahoney** [comment]
Ugh... ktlint has bumped the kotlin version to 1.5.20. So can't upgrade without gradle upgrading their embedded kotlin version.

gradle depending on a specific version of kotlin, and being so slow to update, is a grade a pain.

Mind you, ktlint going up a major version of kotlin in a release that fixes a major performance regression is also less than kind.

**Comment by Mahoney** [comment]
Build passes if I fix the kotlin version.

**Comment by Mahoney** [comment]
Nope, doesn't then work as a plugin. Fail.

**Comment by jeremymailen** [comment]
Hi @Mahoney thanks for the assist. I've been tracking the progress of 0.42.0 and will upgrade soon. Right now it looks like it's got some indent regressions, so I'm waiting in anticipation of a 0.42.1 soon which might address them.

Unless something new has gone sideways with gradle (such as it did before 6.8) it should be possible to take the 1.5.x kotlin upgrade even if have to declare the newest version of kotlinter will require kotlin 1.5.x. This happens periodically because of the dependency on the internal kotlin compiler.

BTW, I do not believe pinterest/ktlint#1135 effects kotlinter. We integrate directly with the `ktlint-core` portion of the library and do not use the file globbing code in the cli component where the performance issue was. Are you seeing performance problems in kotlinter?

**Comment by Mahoney** [comment]
OK, not scientific but having installed the pre push commit hook I had had a couple of times when it felt very slow, saw the performance regression on ktlint and assumed that was it.

It might be that gradle keeps having to spin up a new daemon because of a memory leak somewhere in my build.

**Pull request closed without merging**
