### PR TITLE
Add html reporter

### PR DESCRIPTION
**Pull request by jeremymailen**
Alternative approach would be to allow extensible reporters similar to rulesets.

Addresses #45

### CODE REVIEW

**Comment by jeremymailen** [comment]
@mcassiano let me know what you think. One question I have though is if this will require anyone applying this plugin to their gradle build to add jitpack to their `buildscript` repositories 🤔

**Comment by mcassiano** [comment]
Looks good! I didn't know you'd need to use it directly like this. I think I can arrange publication to jcenter!

**Comment by autonomousapps** [comment]
Excited to see this merged and the next version of kotlinter-gradle published! Thanks, guys :)

**Comment by mcassiano** [comment]
I requested for ktlint-html-reporter to be included in jCenter! Now we wait

**Comment by jeremymailen** [comment]
Perfect, thank you!

I didn't _need_ to use it directly this way. I could have made it extensible, but I think this will be easier for most users. Might still go the other way in the future if there's demand for it.

**Pull request merged**
